const AUTH = {}

AUTH.CHANGE_INPUT = 'AUTH_CHANGE_INPUT'
AUTH.CHANGE_ERROR = 'AUTH_CHANGE_ERROR'
AUTH.SET_ERROR = 'AUTH_SET_ERROR'
AUTH.SET_ALERT = 'AUTH_SET_ALERT'
AUTH.SET_USER = 'AUTH_SET_USER'
AUTH.SET_TOKEN = 'AUTH_SET_TOKEN'
AUTH.LOADING = 'AUTH_LOADING'
AUTH.SET_CHECK_AUTH = 'AUTH_SET_CHECK_AUTH'

export default AUTH
