const POST = {}
const POST_COMMENT = {}
const POST_FORM = {}
const POST_LIST = {}

//Types for selected post
POST.CLEAR = 'POST_CLEAR'
POST.SET_POST = 'POST_SET_POST'
POST.LOADING = 'POST_LOADING'
POST.ERROR = 'POST_ERROR'

//Types for selected post comment
POST_COMMENT.SET_COMMENT = 'POST_COMMENT_SET_COMMENT'
POST_COMMENT.LOADING = 'POST_COMMENT_LOADING'

//Types for postForm
POST_FORM.CHANGE_INPUT = 'POST_FORM_CHANGE_INPUT'
POST_FORM.CLEAR = 'POST_FORM_CLEAR'
POST_FORM.SET_ALERT = 'POST_FORM_SET_ALERT'
POST_FORM.CREATE_POST = 'POST_FORM_CREATE_POST'
POST_FORM.LOADING = 'POSTS_FORM_LOADING'

//Types for all and current user posts
POST_LIST.LOADING = 'POST_LIST_LOADING'
POST_LIST.SET_POSTS = 'POST_LIST_SET_POSTS'
POST_LIST.ADD_POSTS = 'POST_LIST_ADD_POSTS'
POST_LIST.SET_CURRENT_PAGE = 'POST_LIST_SET_CURRENT_PAGE'
POST_LIST.SET_TOTAL_PAGES = 'POST_LIST_SET_TOTAL_PAGES'

export { POST, POST_COMMENT, POST_FORM, POST_LIST }
