const POSTS = {}

//Types for postForm
POSTS.CHANGE_INPUT = 'POSTS_CHANGE_INPUT'
POSTS.CLEAR_POST_FORM = 'POSTS_CLEAR_POST_FORM '
POSTS.SET_ALERT = 'POSTS_SET_ALERT'
POSTS.CREATE_POST= 'POSTS_CREATE_POST'
POSTS.FORM_LOADING = 'POSTS_FORM_LOADING'

//Types for all and current user posts
POSTS.LOADING = 'POSTS_LOADING'
POSTS.SET_POSTS = 'POSTS_SET_POSTS'
POSTS.ADD_POSTS = 'POSTS_ADD_POSTS'
POSTS.SET_CURRENT_PAGE = 'POSTS_SET_CURRENT_PAGE'
POSTS.SET_TOTAL_PAGES = 'POSTS_SET_TOTAL_PAGES'


export default POSTS