const POSTS = {}

POSTS.CHANGE_INPUT = 'POSTS_CHANGE_INPUT'
POSTS.CLEAR_POST_FORM = 'POSTS_CLEAR_POST_FORM '
POSTS.SET_ALERT = 'POSTS_SET_ALERT'
POSTS.CREATE_POST= 'POSTS_CREATE_POST'
POSTS.LOADING = 'POSTS_LOADING'

export default POSTS