export const HOME_ROUTE = "/home"
export const LOGIN_ROUTE = "/login"
export const MY_POSTS_ROUTE = "/post/my"
export const REGISTRATION_ROUTE = "/registration"
export const POST_CREATE_ROUTE = "/post/create"
export const POST_VIEW_ROUTE = "/post/:id"